http:
  middlewares:
    local-only:
      ipAllowList:
        sourceRange:
          - "10.10.22.0/24"

  routers:
    jazztel:
      rule: "Host(`jazztel.skypea.dev`)"
      service: jazztel
      tls:
        certResolver: myresolver
      entrypoints:
        - websecure
      middlewares:
        - local-only
  services:
    jazztel:
      loadBalancer:
        servers:
          - url: "http://10.10.22.1"