http:
  routers:
    jazztel:
      rule: "Host(`jazztel.skypea.dev`)"
      service: jazztel
      tls:
        certResolver: myresolver
      entrypoints:
        - websecure
  services:
    jazztel:
      loadBalancer:
        servers:
          - url: "http://10.10.22.1"